spring:
  application:
    name: medhead

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate